import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  safeAreaView: {
    flex: 1,
    backgroundColor: '#EBE9E0',
  },
  floatingBtn: {
    position: 'absolute',
    width: 60,
    height: 60,
    alignItems: 'center',
    justifyContent: 'center',
    right: 20,
    bottom: 50,
    borderRadius: 25,
    backgroundColor: 'white',
    shadowColor: '#000000',
    shadowRadius: 4,
    shadowOpacity: 0.3,
    shadowOffset: {width: 0, height: 2},
  },
  todoListItem: {
    height: 60,
    width: '84%',
    marginBottom: 20,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    borderRadius: 5,
    shadowColor: '#000000',
    shadowRadius: 3,
    shadowOpacity: 0.2,
    shadowOffset: {width: 2, height: 4},
  },
  addTodoModal: {
    backgroundColor: 'white',
    position: 'absolute',
    bottom: 50,
  },
  swipeLeftContent: {
    height: 60,
    flexDirection: 'row',
    justifyContent: 'flex-end',
  },
  swipeRightContent: {
    height: 60,
    justifyContent: 'center',
  },
  container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: 'black',
  },
  preview: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  capture: {
    flex: 0,
    backgroundColor: '#fff',
    borderRadius: 5,
    padding: 15,
    paddingHorizontal: 20,
    alignSelf: 'center',
    margin: 20,
  },
  greyOutView: {
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 5,
  },
  greyOutMemberList: statusHeight => ({
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    position: 'absolute',
    top: 0,
    height: statusHeight + 90,
    left: 0,
    right: 0,
    zIndex: 5,
  }),
  highlight: {
    backgroundColor: '#EBE9E0',
    height: 74,
    width: 74,
    position: 'absolute',
    borderRadius: 40,
    zIndex: 1,
    borderWidth: 3,
    borderColor: 'red',
  },
  memberListImg: {
    width: 62,
    height: 62,
    borderRadius: 40,
    zIndex: 2,
  },
  memberListItem: {
    height: 74,
    width: 74,
    marginLeft: 10,
    borderRadius: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flatList: {
    height: 90,
    flexGrow: 0,
    borderBottomWidth: 1,
    borderColor: '#484848',
  },
});

export default styles;
